config/routes.rb
Rails.application.routes.draw do  
  devise_for :authes, controllers: { omniauth_callbacks: 'authes/omniauth_callbacks' }

  root "comments#index"  

  resources :quizzes,path_names: {new: "make"}

  resources :comments

  scope '/admin' do
    resources :temps
  end

  resources :user do
    collection do
      post "authenticate"
    end
  end

  resources :people do
    resources :likes,shallow: true
  end

end

app/models/account.rb
class Account < ActiveRecord::Base
 belongs_to :person
 has_one :account_history	
 validates :account_name,presence: true
end

app/models/battery.rb
class Battery < ActiveRecord::Base
	# self.abstract_class = true
	belongs_to :mobile,autosave: true
	validates :name,uniqueness: true

	def method_test
		p "ffff"
	end

	def method_missing(name,args)
		p args
		p "KKKKKKKKKKKKKKKK"
	end

	def method_test
		p "ffff22222"
	end



	# require 'engine'
	# belongs_to :mobile,foreign_key: 'mobile_id'
	# validates :name,numericality: {only_integer: true,greater_than: 20}
	# attr_accessor :gang

	# @@ins = 22

	# arr = ["engine","wheel"]

	# arr.each do |name|

	# 	 define_method("set_#{name}=") do |info|
	# 	 	p "11111111111111111111"
	# 	 	instance_variable_set("@var_#{name}",info)
	# 	 end

	# 	 define_method("get_#{name}") do 
	# 	 	instance_variable_get("@var_#{name}")
	# 	 end

	# 	 define_method("test") do |arg,arg2|
	# 	 	p arg
	# 	 	p arg2
	# 	 end

	# end

	# def get_ins
	# 	@@ins
	# end

	
	# a=Battery.new

	# def test1
 # 		p "test1"
 # 	end

	#  def a.test1
	#  	p "test2"
	#  end	 

	#  a.test1	 
end

app/models/comment.rb
class Comment < ActiveResource::Base
	self.site = "http://localhost:3000"

	def matches?(request)		
	end

end

app/models/contact.rb
class Contact < ActiveRecord::Base
	establish_connection(:adapter => "postgresql",:database => "old_myfam_db",:username=>"postgres",:password=>"postgres")

	def get_phone(num)
		p "NUM"
		p num		
	end

end

app/models/coupan.rb
class Coupan < ActiveRecord::Base
	self.primary_key = 'guid'
end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
	has_many :appointments
	has_many :patients,through: :appointments
end

app/models/engine.rb
module Engine

	def ride_engine
		p "RIDE ENGINE"
	end

	def giri12
		p "GET ENGINE"
	end

end

app/models/like.rb
class Like < ActiveRecord::Base	
	belongs_to :person 
	# validates_associated :person
	# belongs_to :post
	after_touch do 
		p "LIKE"
	end

	after_validation do 
		p "after_validation"
	end

	# before_validation do
	# 	p "before_validation"
	# end

	after_update do 
		p "after_update"
	end
end

app/models/mobile.rb
class Mobile < ActiveRecord::Base	
	has_one :battery
end

app/models/money.rb
class Money < ActiveRecord::Base
end

app/models/patient.rb
class Patient < ActiveRecord::Base
	has_many :appointments
	has_many :doctors,through: :appointments
end

app/models/pay.rb
class Pay < ActiveRecord::Base
end

app/models/person.rb
class Person < ActiveRecord::Base	
	has_many :likes,autosave: true
	has_one :account,autosave: true
	has_one :account_history,through: :account
	validates_associated :account
	# validates_with TestValidator
	# validates :name,presence: true,strict: TestValidatorException
	# validates :name,presence: true,strict: TokenGenerationException	
	# validates :name,acceptance: { accept: "giri",message: 'must be abided' }
	# validates :name,numericality: {only_integer: true}
	# before_save :test,if: Proc.new{false},if: :test2

	# def test
	# 	p "test"
	# end

	# def test2
	# 	true
	# end

	# after_validation do 
	# 	p "after_validation"
	# end

	# before_validation do
	# 	p "before_validation"
	# end

	# after_update do 
	# 	p "after_update"
	# end

	# before_save do
	# 	p "before save"
	# 	raise ActiveRecord::RecordInvalid rescue nil
	# end
	

	# after_rollback do
	# 	p "after_rollback"
	# end

	# after_commit do
	# 	p "after_commit"
	# end	
	def test	
		p "#{cache_key}/#{self.sys_id}"
		Rails.cache.fetch("#{cache_key}/#{self.sys_id}",expires_in: 100000000000.seconds) do
			Person.all
		end
	end

end

app/models/phone.rb
class Phone < Contact

	test = "girish"

	def get_phone(num)
		a=Proc.new {p "saddssd";p "dwswddwwqqd"; return}		
		a.call
		p "GIRISH 22"
	end

end

app/models/post.rb
class Post < ActiveResource::Base	
	self.site = "http://localhost:3000"	
end

app/models/quiz.rb
class Quiz < ActiveRecord::Base
	include QuizzesHelper

	def self.test
		test123
	end

end

app/models/sail.rb
class Sail < ActiveRecord::Base
end

app/models/table.rb
class Table < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base	
	validates_uniqueness_of :email
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i

	def self.validate_sign_up_date(params)
		error_message = nil		
		if params[:email].present?			
			if params[:email].downcase.strip() !~ VALID_EMAIL_REGEX
				error_message = "Enter valid email id"						
			end
		else
			error_message = "Email should be present"			
		end

		if params[:password].size >= 6			
			unless params[:password] == params[:confirm_password]
				error_message += "Password and confirm password dont match"	
			end
		else
			error_message += "Minimum password length is 6"
		end

		if params[:phone].present?
			valid_phone = Integer(params[:phone]) rescue false
			unless valid_phone
				error_message += "Enter valid phone number"
			end
		end
		error_message
	end
end




{"user_name"=>"gjgkgk", 
	"email_id"=>"cjcjv", 
	"password"=>"[FILTERED]", 
	"confirm_password"=>"[FILTERED]", 
	"address"=>"nvnvn", "phone"=>"1234567890"}

app/models/vote.rb
class Vote < ActiveRecord::Base
	belongs_to :post
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  
  before_action :set_quiz, only: [:show, :edit, :update, :destroy]  

  # GET /quizzes
  # GET /quizzes.json
  def index
    # @quizzes = Quiz.all    
    if :var1 == :var1
      puts :var1
    end  
    render json: {data: [{id: 1,name: 'girish'},{id: 2,name: 'raghu'},{id: 3,name: 'guru'},{id: 4,name: 'rev'}]}
  end

  # GET /quizzes/1
  # GET /quizzes/1.json
  def show
  end

  # GET /quizzes/new
  def new
    @quiz = Quiz.new
  end

  # GET /quizzes/1/edit
  def edit
  end

  # POST /quizzes
  # POST /quizzes.json
  def create
    @quiz = Quiz.new(quiz_params)

    respond_to do |format|
      if @quiz.save
        format.html { redirect_to @quiz, notice: 'Quiz was successfully created.' }
        format.json { render :show, status: :created, location: @quiz }
      else
        format.html { render :new }
        format.json { render json: @quiz.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quizzes/1
  # PATCH/PUT /quizzes/1.json
  def update
    respond_to do |format|
      if @quiz.update(quiz_params)
        format.html { redirect_to @quiz, notice: 'Quiz was successfully updated.' }
        format.json { render :show, status: :ok, location: @quiz }
      else
        format.html { render :edit }
        format.json { render json: @quiz.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quizzes/1
  # DELETE /quizzes/1.json
  def destroy
    @quiz.destroy
    respond_to do |format|
      format.html { redirect_to quizzes_url, notice: 'Quiz was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quiz
      @quiz = Quiz.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quiz_params
      params.require(:quiz).permit(:question, :opa, :opb, :opc, :opd, :answer)
    end
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
	def test123
		puts "111111111"
	end
end

app/views/quizzes/_form.html.erb
<%= form_for(@quiz) do |f| %>
  <% if @quiz.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quiz.errors.count, "error") %> prohibited this quiz from being saved:</h2>

      <ul>
      <% @quiz.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :question %><br>
    <%= f.text_area :question %>
  </div>
  <div class="field">
    <%= f.label :opa %><br>
    <%= f.text_field :opa %>
  </div>
  <div class="field">
    <%= f.label :opb %><br>
    <%= f.text_field :opb %>
  </div>
  <div class="field">
    <%= f.label :opc %><br>
    <%= f.text_field :opc %>
  </div>
  <div class="field">
    <%= f.label :opd %><br>
    <%= f.text_field :opd %>
  </div>
  <div class="field">
    <%= f.label :answer %><br>
    <%= f.text_field :answer %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/quizzes/edit.html.erb
<h1>Editing Quiz</h1>

<%= render 'form' %>

<%= link_to 'Show', @quiz %> |
<%= link_to 'Back', quizzes_path %>

app/views/quizzes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Quizzes</h1>

<table>
  <thead>
    <tr>
      <th>Question</th>
      <th>Opa</th>
      <th>Opb</th>
      <th>Opc</th>
      <th>Opd</th>
      <th>Answer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quizzes.each do |quiz| %>
      <tr>
        <td><%= quiz.question %></td>
        <td><%= quiz.opa %></td>
        <td><%= quiz.opb %></td>
        <td><%= quiz.opc %></td>
        <td><%= quiz.opd %></td>
        <td><%= quiz.answer %></td>
        <td><%= link_to 'Show', quiz %></td>
        <td><%= link_to 'Edit', edit_quiz_path(quiz) %></td>
        <td><%= link_to 'Destroy', quiz, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Quiz', new_quiz_path %>

app/views/quizzes/new.html.erb
<h1>New Quiz</h1>

<%= render 'form' %>

<%= link_to 'Back', quizzes_path %>

app/views/quizzes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Question:</strong>
  <%= @quiz.question %>
</p>

<p>
  <strong>Opa:</strong>
  <%= @quiz.opa %>
</p>

<p>
  <strong>Opb:</strong>
  <%= @quiz.opb %>
</p>

<p>
  <strong>Opc:</strong>
  <%= @quiz.opc %>
</p>

<p>
  <strong>Opd:</strong>
  <%= @quiz.opd %>
</p>

<p>
  <strong>Answer:</strong>
  <%= @quiz.answer %>
</p>

<%= link_to 'Edit', edit_quiz_path(@quiz) %> |
<%= link_to 'Back', quizzes_path %>